### ISSUE TITLE
0 byte files

### ISSUE THREAD

**Issue by rmcrackan** [Mbucari/serilog-sinks-zipfile#1]
Libation is getting 0 byte zip logs after upgrading to .net8. Would you mind releasing this nuget as .net8 to see if that helps?

**Comment by Mbucari** [comment]
Ugh, thank god we only have to do this once every 20 years.

May I suggest adding a new text note to Libation repo? "Steps to upgrade .NET"

**Comment by Mbucari** [comment]
@rmcrackan I've updated Serilog.Sinks.ZipFile to 3.1.1 (now matching Serilog's version number).

**Comment by rmcrackan** [comment]
Thanks for the fix. Good idea -- https://github.com/rmcrackan/Libation/blob/master/Source/Upgrading%20dotnet%20version.txt
